import type { BucketShocks, ScenarioShock, ScenarioYear } from "./types";

function path(
  entries: [string, BucketShocks][],
): ScenarioYear[] {
  return entries.map(([label, bucketShocks]) => ({ label, bucketShocks }));
}

/** Crash: sharp drawdown year 1, then gradual recovery */
const CRASH_PATH = path([
  ["Year 1 — Crash", {
    us_equity: -0.3,
    intl_equity: -0.25,
    investment_grade_bond: 0.05,
    long_treasury: 0.12,
    tips: 0.04,
    gold: 0.1,
    commodity: -0.1,
    cash: 0,
    ai_tech: -0.35,
    inverse_equity: 0.55,
    real_estate: -0.15,
    high_yield: -0.08,
  }],
  ["Year 2 — Recovery", {
    us_equity: 0.14,
    intl_equity: 0.1,
    investment_grade_bond: -0.02,
    long_treasury: -0.04,
    tips: 0.01,
    gold: -0.03,
    commodity: 0.05,
    cash: 0.01,
    ai_tech: 0.18,
    inverse_equity: -0.35,
    real_estate: 0.08,
    high_yield: 0.04,
  }],
  ["Year 3 — Normalization", {
    us_equity: 0.08,
    intl_equity: 0.07,
    investment_grade_bond: 0.03,
    long_treasury: 0.02,
    tips: 0.02,
    gold: 0.02,
    commodity: 0.03,
    cash: 0.02,
    ai_tech: 0.1,
    inverse_equity: -0.2,
    real_estate: 0.05,
    high_yield: 0.03,
  }],
  ["Year 4 — Trend growth", {
    us_equity: 0.07,
    intl_equity: 0.06,
    investment_grade_bond: 0.03,
    long_treasury: 0.01,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.02,
    cash: 0.02,
    ai_tech: 0.08,
    inverse_equity: -0.15,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
  ["Year 5 — Trend growth", {
    us_equity: 0.07,
    intl_equity: 0.06,
    investment_grade_bond: 0.03,
    long_treasury: 0.01,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.02,
    cash: 0.02,
    ai_tech: 0.08,
    inverse_equity: -0.15,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
]);

const INFLATION_PATH = path([
  ["Year 1 — Inflation spike", {
    us_equity: -0.05,
    intl_equity: -0.04,
    investment_grade_bond: -0.08,
    long_treasury: -0.12,
    tips: 0.08,
    gold: 0.12,
    commodity: 0.15,
    cash: -0.04,
    ai_tech: -0.08,
    inverse_equity: -0.1,
    real_estate: 0.02,
    high_yield: -0.02,
  }],
  ["Year 2 — Elevated inflation", {
    us_equity: 0.02,
    intl_equity: 0.01,
    investment_grade_bond: -0.04,
    long_treasury: -0.06,
    tips: 0.05,
    gold: 0.06,
    commodity: 0.08,
    cash: -0.03,
    ai_tech: 0,
    inverse_equity: -0.05,
    real_estate: 0.03,
    high_yield: 0.01,
  }],
  ["Year 3 — Disinflation begins", {
    us_equity: 0.06,
    intl_equity: 0.05,
    investment_grade_bond: 0.04,
    long_treasury: 0.05,
    tips: 0.02,
    gold: -0.02,
    commodity: -0.03,
    cash: 0.01,
    ai_tech: 0.07,
    inverse_equity: -0.08,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
  ["Year 4 — Normalizing", {
    us_equity: 0.07,
    intl_equity: 0.06,
    investment_grade_bond: 0.03,
    long_treasury: 0.02,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.01,
    cash: 0.02,
    ai_tech: 0.08,
    inverse_equity: -0.1,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
  ["Year 5 — Normalizing", {
    us_equity: 0.07,
    intl_equity: 0.06,
    investment_grade_bond: 0.03,
    long_treasury: 0.02,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.01,
    cash: 0.02,
    ai_tech: 0.08,
    inverse_equity: -0.1,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
]);

const AI_BUST_PATH = path([
  ["Year 1 — AI de-rating", {
    us_equity: -0.1,
    intl_equity: -0.08,
    investment_grade_bond: 0.04,
    long_treasury: 0.05,
    tips: 0.02,
    gold: 0.05,
    commodity: -0.05,
    cash: 0.01,
    ai_tech: -0.4,
    inverse_equity: 0.2,
    real_estate: -0.05,
    high_yield: -0.03,
  }],
  ["Year 2 — CapEx unwind", {
    us_equity: -0.05,
    intl_equity: -0.04,
    investment_grade_bond: 0.03,
    long_treasury: 0.02,
    tips: 0.01,
    gold: 0.02,
    commodity: 0,
    cash: 0.01,
    ai_tech: -0.15,
    inverse_equity: 0.1,
    real_estate: 0,
    high_yield: 0.01,
  }],
  ["Year 3 — Selective recovery", {
    us_equity: 0.06,
    intl_equity: 0.05,
    investment_grade_bond: 0.03,
    long_treasury: 0.01,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.02,
    cash: 0.02,
    ai_tech: 0.05,
    inverse_equity: -0.15,
    real_estate: 0.03,
    high_yield: 0.02,
  }],
  ["Year 4 — New equilibrium", {
    us_equity: 0.07,
    intl_equity: 0.06,
    investment_grade_bond: 0.03,
    long_treasury: 0.01,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.02,
    cash: 0.02,
    ai_tech: 0.06,
    inverse_equity: -0.12,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
  ["Year 5 — New equilibrium", {
    us_equity: 0.07,
    intl_equity: 0.06,
    investment_grade_bond: 0.03,
    long_treasury: 0.01,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.02,
    cash: 0.02,
    ai_tech: 0.06,
    inverse_equity: -0.12,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
]);

const STAGFLATION_PATH = path([
  ["Year 1 — Stagflation shock", {
    us_equity: -0.2,
    intl_equity: -0.18,
    investment_grade_bond: -0.12,
    long_treasury: -0.15,
    tips: 0.1,
    gold: 0.15,
    commodity: 0.1,
    cash: -0.03,
    ai_tech: -0.25,
    inverse_equity: 0.12,
    real_estate: -0.08,
    high_yield: -0.06,
  }],
  ["Year 2 — Persisting", {
    us_equity: -0.05,
    intl_equity: -0.04,
    investment_grade_bond: -0.06,
    long_treasury: -0.08,
    tips: 0.06,
    gold: 0.08,
    commodity: 0.05,
    cash: -0.02,
    ai_tech: -0.08,
    inverse_equity: 0.05,
    real_estate: -0.02,
    high_yield: -0.03,
  }],
  ["Year 3 — Slow improvement", {
    us_equity: 0.03,
    intl_equity: 0.02,
    investment_grade_bond: 0.02,
    long_treasury: 0.01,
    tips: 0.04,
    gold: 0.03,
    commodity: 0.02,
    cash: 0,
    ai_tech: 0.02,
    inverse_equity: -0.05,
    real_estate: 0.02,
    high_yield: 0.01,
  }],
  ["Year 4 — Recovery", {
    us_equity: 0.06,
    intl_equity: 0.05,
    investment_grade_bond: 0.03,
    long_treasury: 0.02,
    tips: 0.03,
    gold: 0.01,
    commodity: 0.01,
    cash: 0.01,
    ai_tech: 0.06,
    inverse_equity: -0.08,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
  ["Year 5 — Recovery", {
    us_equity: 0.06,
    intl_equity: 0.05,
    investment_grade_bond: 0.03,
    long_treasury: 0.02,
    tips: 0.03,
    gold: 0.01,
    commodity: 0.01,
    cash: 0.01,
    ai_tech: 0.06,
    inverse_equity: -0.08,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
]);

const OPENAI_PATH = path([
  ["Year 1 — OpenAI stress", {
    us_equity: -0.05,
    intl_equity: -0.03,
    investment_grade_bond: 0.02,
    long_treasury: 0.03,
    tips: 0,
    gold: 0.02,
    commodity: 0,
    cash: 0,
    ai_tech: -0.25,
    inverse_equity: 0.08,
    real_estate: -0.02,
    high_yield: 0,
  }],
  ["Year 2 — Sector rotation", {
    us_equity: 0.03,
    intl_equity: 0.02,
    investment_grade_bond: 0.02,
    long_treasury: 0.01,
    tips: 0.01,
    gold: 0.01,
    commodity: 0,
    cash: 0.01,
    ai_tech: -0.05,
    inverse_equity: -0.05,
    real_estate: 0.02,
    high_yield: 0.01,
  }],
  ["Year 3 — Stabilization", {
    us_equity: 0.06,
    intl_equity: 0.05,
    investment_grade_bond: 0.03,
    long_treasury: 0.01,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.01,
    cash: 0.02,
    ai_tech: 0.04,
    inverse_equity: -0.1,
    real_estate: 0.03,
    high_yield: 0.02,
  }],
  ["Year 4 — Trend", {
    us_equity: 0.07,
    intl_equity: 0.06,
    investment_grade_bond: 0.03,
    long_treasury: 0.01,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.02,
    cash: 0.02,
    ai_tech: 0.07,
    inverse_equity: -0.12,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
  ["Year 5 — Trend", {
    us_equity: 0.07,
    intl_equity: 0.06,
    investment_grade_bond: 0.03,
    long_treasury: 0.01,
    tips: 0.02,
    gold: 0.01,
    commodity: 0.02,
    cash: 0.02,
    ai_tech: 0.07,
    inverse_equity: -0.12,
    real_estate: 0.04,
    high_yield: 0.03,
  }],
]);

export const SCENARIOS: ScenarioShock[] = [
  {
    id: "inflation_spike",
    name: "High Inflation (+6% CPI)",
    description:
      "Persistent inflation erodes purchasing power. TIPS, gold, and commodities outperform; long bonds suffer. Shocks apply to each fund based on its asset mix.",
    defaultForecastYears: 5,
    yearlyPath: INFLATION_PATH,
    hedgeSuggestions: [
      "Add TIPS (TIP) — 10–20% allocation",
      "Add commodities (PDBC) or gold (GLD) — 5–15%",
      "Reduce long-duration bonds (TLT)",
    ],
  },
  {
    id: "market_crash",
    name: "Stock Market Crash (-30% S&P)",
    description:
      "Sharp equity selloff in year 1. Only the equity portion of each fund drops ~30%; bond funds rally as investors flee to quality.",
    defaultForecastYears: 5,
    yearlyPath: CRASH_PATH,
    hedgeSuggestions: [
      "Hold 5–10% cash for rebalancing",
      "Index put options (SPY/SPX) as insurance",
      "Small allocation to gold (GLD) — 5–10%",
    ],
  },
  {
    id: "ai_bust",
    name: "AI Bubble Deflates",
    description:
      "AI/growth names de-rate sharply; bond and value holdings hold up better. Mixed funds lose less than pure AI stocks.",
    defaultForecastYears: 5,
    yearlyPath: AI_BUST_PATH,
    tickerShocks: {
      NVDA: -0.45,
      PLTR: -0.5,
      SMCI: -0.55,
    },
    hedgeSuggestions: [
      "Reduce concentrated AI exposure (NVDA, PLTR, SMCI)",
      "Increase investment-grade bond allocation (BND, AGG)",
    ],
  },
  {
    id: "stagflation",
    name: "Stagflation",
    description:
      "Inflation rises while growth stalls. Real assets help; both stocks and nominal bonds pressured.",
    defaultForecastYears: 5,
    yearlyPath: STAGFLATION_PATH,
    hedgeSuggestions: [
      "TIPS + commodities + gold barbell",
      "Avoid long-duration bonds",
    ],
  },
  {
    id: "openai_indirect",
    name: "OpenAI / ChatGPT Failure (Indirect)",
    description:
      "OpenAI loses share; MSFT and AI infra hit, bond funds largely unaffected.",
    defaultForecastYears: 5,
    yearlyPath: OPENAI_PATH,
    tickerShocks: {
      MSFT: -0.15,
      NVDA: -0.2,
      GOOGL: 0.05,
      GOOG: 0.05,
    },
    hedgeSuggestions: [
      "Put options on MSFT (largest public OpenAI exposure)",
      "Long Google as relative winner if OpenAI falters",
    ],
  },
];

export function getScenario(id: string): ScenarioShock | undefined {
  return SCENARIOS.find((s) => s.id === id);
}

export function getScenarioYears(
  scenario: ScenarioShock,
  forecastYears: number,
): ScenarioYear[] {
  const years = Math.max(1, Math.min(forecastYears, 10));
  const path = scenario.yearlyPath;
  if (years <= path.length) return path.slice(0, years);
  const last = path[path.length - 1];
  const extended = [...path];
  for (let i = path.length; i < years; i++) {
    extended.push({
      label: `Year ${i + 1} — Trend growth`,
      bucketShocks: last.bucketShocks,
    });
  }
  return extended;
}
